"""
Unified fabric scanner for the UR5e.

This module owns the current robot fabric-scanning workflow: scan planning,
URScript export/sending, MuJoCo visualization, robot-camera image capture,
scanner lighting, and RGB-analysis helpers used by the main app.
"""

from __future__ import annotations

import json
import math
import socket
from dataclasses import dataclass, replace
from pathlib import Path

import numpy as np
from PIL import Image, ImageFilter
from scipy.spatial.transform import Rotation
from knitting_core import build_parametric_control_rows
import paths


# ============================================================================
# Scanner Runtime Constants
# ============================================================================

# Robot planning constants.
DEFAULT_MAX_SPAN = np.array([0.30, 0.22, 0.04], dtype=float)
TOOL_DOWN_ROTVEC = np.array([math.pi, 0.0, 0.0], dtype=float)
UR5_REACH_MAX = 0.850
UR5_REACH_MIN = 0.180
UR5_MIN_XY_RADIUS = 0.150
# MuJoCo/IK tuning and scene drawing constants.
MUJOCO_DAMPING = 1e-2
MUJOCO_KP = 0.28
IK_SUBSTEPS = 3
TARGET_TOL = 0.006
TARGET_ROT_TOL = 0.08
MAX_TRAIL_POINTS = 6000
MARKER_RADIUS = 0.006
PATH_WIDTH = 0.003
POSE_AXIS_LENGTH = 0.035
FABRIC_THICKNESS = 0.003
IMAGE_REPEAT_OVERLAP = 1.68
SCAN_PATTERN_FILL = 1.08
CAMERA_MARKER_SIZE = np.array([0.018, 0.012, 0.010])
CAMERA_IMAGE_SIZE = (1024, 768)
CAMERA_SAVE_EVERY_STATION = "station"
CAMERA_SAVE_EVERY_VIEW = "view"
CAMERA_CAPTURE_NATURAL = "natural"
CAMERA_CAPTURE_FOCUSED = "focused"
NON_SCAN_VIEW_NAMES = {"approach", "retreat", "travel"}
ROBOT_MAX_CARTESIAN_STEP = 0.040


# ============================================================================
# Robot Planning Section
# ============================================================================

def fit_path_to_workspace(points: np.ndarray, center: np.ndarray, max_span: np.ndarray) -> np.ndarray:
    """Scale and translate local scanner points into the UR5 base workspace."""
    points = np.asarray(points, dtype=float)
    span = np.maximum(points.max(axis=0) - points.min(axis=0), 1e-9)
    scale = float(np.min(max_span / span))
    return (points - points.mean(axis=0)) * scale + center


def points_and_rotvecs_to_poses(points: np.ndarray, rotvecs: np.ndarray) -> np.ndarray:
    """Convert XYZ points plus per-stop orientations to URScript poses."""
    return np.hstack([points, rotvecs])


def generate_urscript(
    poses: np.ndarray,
    accel: float,
    vel: float,
    blend_r: float,
    dwell: float,
    station_ids: list[int] | None = None,
    view_names: list[str] | None = None,
    prog_name: str = "fabric_scanner",
) -> str:
    lines = [
        "# URScript - generated by fabric_scanner.py",
        "# Cartesian fabric scan for UR5 / URSim",
        f"# Waypoints : {len(poses)}",
        f"# Accel     : {accel}  Vel: {vel}  Blend: {blend_r}",
        "",
        f"def {prog_name}():",
        "  set_tcp(p[0.000000, 0.000000, 0.120000, 0.000000, 0.000000, 0.000000])",
        "  # Move to the first scan pose slowly.",
        f"  movej(p[{', '.join(f'{v:.6f}' for v in poses[0])}], a=0.15, v=0.05, r=0)",
        "",
        "  # Fabric scan stops. URSim solves IK for each Cartesian pose.",
    ]
    for i, pose in enumerate(poses):
        if station_ids is not None and view_names is not None:
            lines.append(f"  # station {station_ids[i] + 1}: {view_names[i]}")
        pose_str = ", ".join(f"{v:.6f}" for v in pose)
        lines.append(f"  movel(p[{pose_str}], a={accel}, v={vel}, r={blend_r})")
        lines.append(f"  sleep({dwell})")
    lines += ["end", "", f"{prog_name}()"]
    return "\n".join(lines)


def assess_plan_safety(points: np.ndarray, max_step: float = 0.035) -> tuple[bool, list[str]]:
    issues: list[str] = []
    points = np.asarray(points, dtype=float)
    reach = np.linalg.norm(points, axis=1)
    xy_radius = np.linalg.norm(points[:, :2], axis=1)
    if float(np.max(reach)) > UR5_REACH_MAX:
        issues.append(f"max reach is {float(np.max(reach)):.3f} m, above UR5 reach {UR5_REACH_MAX:.3f} m")
    if float(np.min(reach)) < UR5_REACH_MIN:
        issues.append(f"min reach is {float(np.min(reach)):.3f} m, inside inner reach {UR5_REACH_MIN:.3f} m")
    if float(np.min(xy_radius)) < UR5_MIN_XY_RADIUS:
        issues.append(f"min XY radius is {float(np.min(xy_radius)):.3f} m, too close to base column")
    if float(np.min(points[:, 2])) < 0.05:
        issues.append(f"min Z is {float(np.min(points[:, 2])):.3f} m, too close to the table/base")
    if len(points) > 1:
        steps = np.linalg.norm(np.diff(points, axis=0), axis=1)
        if float(np.max(steps)) > max_step:
            issues.append(f"max Cartesian step is {float(np.max(steps)):.3f} m, above limit {max_step:.3f} m")
    return len(issues) == 0, issues
# ============================================================================
# Lighting Section
# ============================================================================

# Scanner lighting is applied to the image-based repeated fabric texture. This
# keeps Scan Mode lightweight while still adding asymmetric shading and sheen.
SCANNER_SUN_AZIMUTH_DEG = -35.0
SCANNER_SUN_ELEVATION_DEG = 48.0
SCANNER_AMBIENT_LIGHT = 0.38
SCANNER_SUN_INTENSITY = 0.68
SCANNER_SIDE_SHADOW = 0.20
SCANNER_SPECULAR_STRENGTH = 0.055
SCANNER_SHEEN_STRENGTH = 0.025
SCANNER_FABRIC_GRADIENT_STRENGTH = 0.14
SCANNER_FABRIC_VIGNETTE_STRENGTH = 0.06
SCANNER_LIGHTING_BLUR_RADIUS = 1.35
SCANNER_LIGHTING_RELIEF = 1.45
SCANNER_LIGHTING_FOCUSED_RELIEF = 1.75


def _default_scanner_lighting() -> dict[str, float]:
    return {
        "enabled": 1.0,
        "azimuth": SCANNER_SUN_AZIMUTH_DEG,
        "elevation": SCANNER_SUN_ELEVATION_DEG,
        "ambient": SCANNER_AMBIENT_LIGHT,
        "sun_intensity": SCANNER_SUN_INTENSITY,
        "shadow": SCANNER_SIDE_SHADOW,
        "specular": SCANNER_SPECULAR_STRENGTH,
        "sheen": SCANNER_SHEEN_STRENGTH,
        "gradient": SCANNER_FABRIC_GRADIENT_STRENGTH,
        "vignette": SCANNER_FABRIC_VIGNETTE_STRENGTH,
        "blur": SCANNER_LIGHTING_BLUR_RADIUS,
        "relief": SCANNER_LIGHTING_RELIEF,
        "focused_relief": SCANNER_LIGHTING_FOCUSED_RELIEF,
    }


def _normalize_scanner_lighting(settings=None) -> dict[str, float]:
    lighting = _default_scanner_lighting()
    if isinstance(settings, dict):
        for key, value in settings.items():
            if key in lighting:
                try:
                    lighting[key] = float(value)
                except (TypeError, ValueError):
                    pass
    lighting["elevation"] = float(np.clip(lighting["elevation"], 5.0, 85.0))
    lighting["enabled"] = 1.0 if float(lighting.get("enabled", 1.0)) >= 0.5 else 0.0
    lighting["ambient"] = float(np.clip(lighting["ambient"], 0.10, 0.90))
    lighting["sun_intensity"] = float(np.clip(lighting["sun_intensity"], 0.0, 1.50))
    lighting["shadow"] = float(np.clip(lighting["shadow"], 0.0, 0.60))
    lighting["specular"] = float(np.clip(lighting["specular"], 0.0, 0.25))
    lighting["sheen"] = float(np.clip(lighting["sheen"], 0.0, 0.16))
    lighting["gradient"] = float(np.clip(lighting["gradient"], 0.0, 0.45))
    lighting["vignette"] = float(np.clip(lighting["vignette"], 0.0, 0.25))
    lighting["blur"] = float(np.clip(lighting["blur"], 0.0, 4.0))
    lighting["relief"] = float(np.clip(lighting["relief"], 0.0, 4.0))
    lighting["focused_relief"] = float(np.clip(lighting["focused_relief"], 0.0, 4.0))
    return lighting


def _scanner_lighting_from_args(args) -> dict[str, float]:
    settings = getattr(args, "scanner_lighting", None)
    if isinstance(settings, dict):
        return _normalize_scanner_lighting(settings)
    return _normalize_scanner_lighting({
        "azimuth": getattr(args, "scanner_light_azimuth", SCANNER_SUN_AZIMUTH_DEG),
        "enabled": 0.0 if bool(getattr(args, "no_scanner_lighting", False)) else 1.0,
        "elevation": getattr(args, "scanner_light_elevation", SCANNER_SUN_ELEVATION_DEG),
        "sun_intensity": getattr(args, "scanner_light_sun_intensity", SCANNER_SUN_INTENSITY),
        "shadow": getattr(args, "scanner_light_shadow", SCANNER_SIDE_SHADOW),
        "sheen": getattr(args, "scanner_light_sheen", SCANNER_SHEEN_STRENGTH),
    })


# ============================================================================
# Fabric Planning and Pattern Data
# ============================================================================

SWATCH_PALETTE = [
    (0.86, 0.12, 0.18, 1.0),
    (0.10, 0.39, 0.82, 1.0),
    (0.98, 0.78, 0.16, 1.0),
    (0.12, 0.62, 0.36, 1.0),
    (0.78, 0.18, 0.72, 1.0),
    (0.96, 0.43, 0.16, 1.0),
    (0.12, 0.70, 0.76, 1.0),
    (0.47, 0.34, 0.85, 1.0),
]


@dataclass
class FabricPlan:
    raw_stations: np.ndarray
    mapped_stations: np.ndarray
    raw_points: np.ndarray
    mapped_points: np.ndarray
    poses: np.ndarray
    station_ids: list[int]
    view_names: list[str]
    station_cells: list[tuple[int, int]]
    cell_colors: list[tuple[float, float, float, float]]
    cell_color_sets: list[list[tuple[float, float, float, float]]]
    fabric_origin: np.ndarray
    fabric_size: np.ndarray
    grid_rows: int
    grid_cols: int
    square_width: float
    square_length: float
    model_curves: list[np.ndarray]
    cell_model_curves: list[list[np.ndarray]] | None = None
    pattern_repeat_rows: int = 1
    pattern_repeat_cols: int = 1
    pattern_repeat_spacing_x: float = 1.0
    pattern_repeat_spacing_y: float = 1.0
    batch_texture_width: int = 420
    batch_texture_height: int = 340
    scanner_lighting: dict[str, float] | None = None
    display_batch_colors: list[tuple[float, float, float, float]] | None = None


def _serpentine_indices(rows: int, cols: int):
    for row in range(rows):
        col_range = range(cols) if row % 2 == 0 else range(cols - 1, -1, -1)
        for col in col_range:
            yield row, col


def _normalize_palette(palette) -> list[tuple[float, float, float, float]]:
    if palette is None:
        return list(SWATCH_PALETTE)
    if isinstance(palette, np.ndarray):
        palette = palette.tolist()
    if (
        isinstance(palette, (list, tuple))
        and len(palette) >= 3
        and all(isinstance(v, (int, float, np.integer, np.floating)) for v in palette[:3])
    ):
        r, g, b = [float(v) for v in palette[:3]]
        a = float(palette[3]) if len(palette) > 3 else 1.0
        return [(r, g, b, a)]

    colors = []
    for color in palette or []:
        if isinstance(color, np.ndarray):
            color = color.tolist()
        if not isinstance(color, (list, tuple)) or len(color) < 3:
            continue
        r, g, b = [float(v) for v in color[:3]]
        a = float(color[3]) if len(color) > 3 else 1.0
        colors.append((r, g, b, a))
    return colors or list(SWATCH_PALETTE)


def _normalize_batch_display_colors(colors, count: int) -> list[tuple[float, float, float, float]] | None:
    if colors is None:
        return None
    normalized: list[tuple[float, float, float, float]] = []
    for color in colors:
        if isinstance(color, np.ndarray):
            color = color.tolist()
        if not isinstance(color, (list, tuple)) or len(color) < 3:
            continue
        rgb = [float(color[i]) for i in range(3)]
        if max(rgb) > 1.0:
            rgb = [v / 255.0 for v in rgb]
        alpha = float(color[3]) if len(color) > 3 else 1.0
        normalized.append((
            float(np.clip(rgb[0], 0.0, 1.0)),
            float(np.clip(rgb[1], 0.0, 1.0)),
            float(np.clip(rgb[2], 0.0, 1.0)),
            float(np.clip(alpha, 0.0, 1.0)),
        ))
        if len(normalized) >= count:
            break
    return normalized or None


# ============================================================================
# Fabric Model Loading and Random Pattern Generation
# ============================================================================

def _fallback_model_curves() -> list[np.ndarray]:
    return [
        np.asarray(curve, dtype=np.float32)
        for curve in _knit_cell_curves()
    ]


def _load_saved_model_curves(model_json: str | None) -> list[np.ndarray]:
    if not model_json:
        return _fallback_model_curves()

    path = Path(model_json)
    if not path.exists():
        return _fallback_model_curves()

    try:
        with path.open("r") as handle:
            saved = json.load(handle)

        ctrl_rows = [
            np.asarray(row, dtype=np.float32)
            for row in saved.get("spline_control_rows", [])
            if len(row) > 1
        ]
        if not ctrl_rows:
            return _fallback_model_curves()

        bitmap = np.asarray(saved.get("bitmap", np.ones((len(ctrl_rows), 1))), dtype=np.float32)
        # "period_offset" is the pre-split key; model files written before the
        # x/y split still carry it, so fall back to it before the bitmap default.
        saved_period = saved.get("period_offset_x", saved.get("period_offset"))
        if saved_period is None:
            saved_period = [float(max(1, bitmap.shape[1])), 0.0, 0.0]
        period = np.asarray(saved_period, dtype=np.float32)

        curves = []
        for row_idx, row in enumerate(ctrl_rows):
            cp = np.asarray(row[:, :2], dtype=np.float32)
            cp_aug = np.vstack((cp, cp[0] + period[:2]))
            seg_lens = np.maximum(np.linalg.norm(np.diff(cp_aug, axis=0), axis=1), 1e-6)
            t = np.concatenate(([0.0], np.cumsum(seg_lens)))
            samples = max(80, len(cp) * 8)
            to = np.linspace(t[0], t[-1], samples, dtype=np.float32)
            detrended = cp_aug - period[:2][None, :] * (t / t[-1])[:, None]
            if len(cp) == 2:
                pts = np.column_stack([np.interp(to, t, detrended[:, i]) for i in range(2)])
            else:
                from scipy.interpolate import CubicSpline
                pts = np.column_stack([CubicSpline(t, detrended[:, i], bc_type="periodic")(to) for i in range(2)])
            pts = pts + period[:2][None, :] * (to / t[-1])[:, None]

            if row_idx < bitmap.shape[0]:
                straight_cols = np.flatnonzero(np.asarray(bitmap[row_idx], dtype=np.float32) <= 0.5)
                if len(straight_cols):
                    samples_per_col = max(1, len(cp) // max(1, bitmap.shape[1]))
                    for col_idx in straight_cols:
                        start = int(col_idx) * samples_per_col
                        end = min((int(col_idx) + 1) * samples_per_col, len(cp_aug) - 1)
                        if end <= start:
                            continue
                        t0, t1 = float(t[start]), float(t[end])
                        span = (to >= t0) & (to <= t1)
                        if np.any(span):
                            alpha = ((to[span] - t0) / max(t1 - t0, 1e-6))[:, None]
                            pts[span] = cp_aug[start] * (1.0 - alpha) + cp_aug[end] * alpha

            curves.append(pts.astype(np.float32))

        if not curves:
            return _fallback_model_curves()

        all_pts = np.vstack(curves)
        min_xy = all_pts.min(axis=0)
        max_xy = all_pts.max(axis=0)
        span = np.maximum(max_xy - min_xy, 1e-6)
        scale = 0.92 / float(max(span[0], span[1]))
        center = (min_xy + max_xy) * 0.5
        normalized = [
            ((curve - center) * scale).astype(np.float32)
            for curve in curves
        ]
        return normalized
    except Exception as exc:
        print(f"[scanner] could not load edited model from {model_json}: {exc}")
        return _fallback_model_curves()


def _default_cell_color_set(row: int, col: int, palette=None) -> list[tuple[float, float, float, float]]:
    colors = _normalize_palette(palette)
    start = (row * 3 + col * 5 + row * col) % len(colors)
    return [colors[(start + i) % len(colors)] for i in range(4)]


def _normalize_cell_color_sets(raw_sets, rows: int, cols: int, palette=None) -> list[list[tuple[float, float, float, float]]]:
    normalized: list[list[tuple[float, float, float, float]]] = []
    flat_sets = raw_sets if isinstance(raw_sets, list) and len(raw_sets) == rows * cols else None
    for row in range(rows):
        for col in range(cols):
            raw_cell = None
            if flat_sets is not None:
                raw_cell = flat_sets[row * cols + col]
            else:
                try:
                    raw_cell = raw_sets[row][col]
                except Exception:
                    raw_cell = None
            color_set = _normalize_palette(raw_cell)
            if not raw_cell or len(color_set) < 4:
                if color_set:
                    color_set = [color_set[0] for _ in range(4)]
                else:
                    color_set = _default_cell_color_set(row, col, palette)
            normalized.append(color_set[:4])
    return normalized


def _normalize_cell_model_curves(raw_sets, rows: int, cols: int) -> list[list[np.ndarray]] | None:
    if not isinstance(raw_sets, (list, tuple)) or len(raw_sets) != rows * cols:
        return None
    normalized: list[list[np.ndarray]] = []
    for cell in raw_sets:
        curves = []
        if isinstance(cell, (list, tuple)):
            for curve in cell:
                arr = np.asarray(curve, dtype=np.float32)
                if arr.ndim == 2 and arr.shape[0] > 1 and arr.shape[1] >= 2:
                    curves.append(arr[:, :2].astype(np.float32))
        normalized.append(curves)
    return normalized if any(normalized) else None


def normalize_model_curves(curves, *, fallback=None) -> list[np.ndarray]:
    """Centre a set of 2D curves and scale them to fill the scan pattern cell.

    Shared with Scan Mode's own pattern generation, which wants an empty list
    rather than the built-in fallback shape when there is nothing to normalize
    -- that is the only way the two callers differ.
    """
    valid = [np.asarray(curve, dtype=np.float32)[:, :2] for curve in curves if len(curve) > 1]
    if not valid:
        return _fallback_model_curves() if fallback is None else fallback
    pts = np.vstack(valid)
    min_xy = pts.min(axis=0)
    max_xy = pts.max(axis=0)
    span = np.maximum(max_xy - min_xy, 1e-6)
    center = (min_xy + max_xy) * 0.5
    scale = SCAN_PATTERN_FILL / float(max(span[0], span[1]))
    return [((curve - center) * scale).astype(np.float32) for curve in valid]


def _scanner_param_context(model_json: str | None):
    with paths.CONFIG_JSON.open("r") as handle:
        config = json.load(handle)
    params = np.asarray([p["initial"] for p in config["knit_parameters"]["parameters"]], dtype=np.float32)
    samples_per_loop = 5
    saved_loop_heights = None
    if model_json and Path(model_json).exists():
        try:
            with Path(model_json).open("r") as handle:
                saved = json.load(handle)
            if "params" in saved:
                if isinstance(saved["params"], dict):
                    loaded_params = params.copy()
                    for name, value in saved["params"].items():
                        index = next(
                            (
                                idx
                                for idx, param in enumerate(config["knit_parameters"]["parameters"])
                                if param["name"] == name
                            ),
                            None,
                        )
                        if index is not None:
                            loaded_params[index] = float(value)
                else:
                    loaded_params = np.asarray(saved["params"], dtype=np.float32)
                if loaded_params.shape == params.shape:
                    params = loaded_params
            if "samples_per_loop" in saved:
                samples_per_loop = int(saved.get("samples_per_loop", samples_per_loop))
            elif isinstance(saved.get("gui_state"), dict) and "samples_per_loop" in saved["gui_state"]:
                samples_per_loop = int(saved["gui_state"].get("samples_per_loop", samples_per_loop))
            raw_loop_heights = saved.get("loop_heights")
            if raw_loop_heights is None and isinstance(saved.get("gui_state"), dict):
                raw_loop_heights = saved["gui_state"].get("loop_heights")
            if raw_loop_heights is not None:
                saved_loop_heights = np.asarray(raw_loop_heights, dtype=np.float32)
        except Exception as exc:
            print(f"[scanner] could not read param context from {model_json}: {exc}")
    pidx = {p["name"]: i for i, p in enumerate(config["knit_parameters"]["parameters"])}
    lh_names = sorted(
        [p["name"] for p in config["knit_parameters"]["parameters"] if p["name"].startswith("loop_height_")],
        key=lambda name: int(name.split("_")[-1]),
    )
    lh_idx = tuple(pidx[name] for name in lh_names)
    return params, pidx, lh_idx, samples_per_loop, saved_loop_heights


def _loop_heights_for_random_bitmap(params, bitmap, lh_idx, saved_loop_heights):
    heights = np.zeros_like(bitmap, dtype=np.float32)
    for row_idx in range(bitmap.shape[0]):
        if lh_idx:
            heights[row_idx, :] = float(params[lh_idx[min(row_idx, len(lh_idx) - 1)]])
        else:
            heights[row_idx, :] = 3.0
    saved = np.asarray(saved_loop_heights, dtype=np.float32) if saved_loop_heights is not None else np.empty((0, 0), dtype=np.float32)
    if saved.ndim == 2 and saved.size:
        keep_rows = min(bitmap.shape[0], saved.shape[0])
        keep_cols = min(bitmap.shape[1], saved.shape[1])
        heights[:keep_rows, :keep_cols] = saved[:keep_rows, :keep_cols]
    return heights * (bitmap > 0.5)


def _random_bitmap_model_curves(
    pattern_rows: int,
    pattern_cols: int,
    seed: int,
    density: float,
    repeat_rows: int = 3,
    repeat_cols: int = 3,
    model_json: str | None = None,
) -> list[np.ndarray]:
    rng = np.random.default_rng(int(seed))
    pattern_rows = max(2, int(pattern_rows))
    pattern_cols = max(2, int(pattern_cols))
    density = float(np.clip(density, 0.05, 0.95))
    bitmap = (rng.random((pattern_rows, pattern_cols)) < density).astype(np.float32)
    if not np.any(bitmap > 0.5):
        bitmap[rng.integers(0, pattern_rows), rng.integers(0, pattern_cols)] = 1.0

    params, pidx, lh_idx, samples_per_loop, saved_loop_heights = _scanner_param_context(model_json)
    loop_heights = _loop_heights_for_random_bitmap(params, bitmap, lh_idx, saved_loop_heights)
    curves = build_parametric_control_rows(
        params,
        bitmap,
        pidx,
        lh_idx,
        samples_per_loop,
        loop_heights=loop_heights,
    )
    return normalize_model_curves(curves)


def _generate_random_cell_model_curves(args) -> list[list[np.ndarray]]:
    rows = max(1, int(args.rows))
    cols = max(1, int(args.cols))
    seed = int(getattr(args, "random_seed", 1))
    pattern_rows = int(getattr(args, "pattern_rows", 4))
    pattern_cols = int(getattr(args, "pattern_cols", 5))
    repeat_rows = int(getattr(args, "pattern_repeat_rows", 3))
    repeat_cols = int(getattr(args, "pattern_repeat_cols", 3))
    density = float(getattr(args, "pattern_density", 0.62))
    return [
        _random_bitmap_model_curves(
            pattern_rows,
            pattern_cols,
            seed + cell * 9973,
            density,
            repeat_rows,
            repeat_cols,
            getattr(args, "model_json", ""),
        )
        for cell in range(rows * cols)
    ]


# ============================================================================
# Scanning Section: Stations, Angles, and Scan Plan
# ============================================================================

def build_fabric_grid_stations(
    width: float,
    length: float,
    rows: int,
    cols: int,
    edge_margin: float,
    square_margin: float,
    surface_wave: float,
    palette=None,
    cell_color_sets=None,
) -> tuple[np.ndarray, list[tuple[int, int]], list[tuple[float, float, float, float]], list[list[tuple[float, float, float, float]]]]:
    if min(width, length) <= 0:
        raise ValueError("fabric width and length must be positive")
    if min(rows, cols) <= 0:
        raise ValueError("grid counts must be positive")

    cell_w = width / cols
    cell_l = length / rows
    stations: list[list[float]] = []
    cells: list[tuple[int, int]] = []
    colors: list[tuple[float, float, float, float]] = []
    all_cell_color_sets = _normalize_cell_color_sets(cell_color_sets, rows, cols, palette)

    for row, col in _serpentine_indices(rows, cols):
        x0 = -width / 2 + col * cell_w
        y0 = -length / 2 + row * cell_l
        x = x0 + cell_w * 0.5
        y = y0 + cell_l * 0.5
        z = surface_wave * math.sin(2 * math.pi * (x / width + 0.5))
        z += 0.5 * surface_wave * math.cos(2 * math.pi * (y / length + 0.5))
        stations.append([float(x), float(y), float(z)])
        cells.append((row, col))
        colors.append(all_cell_color_sets[row * cols + col][0])

    return np.asarray(stations, dtype=float), cells, colors, all_cell_color_sets


def expand_stations_to_angle_viewpoints(
    stations: np.ndarray,
    number_of_angles: int,
    view_radius: float,
    angle_lift: float,
) -> tuple[np.ndarray, list[int], list[str], np.ndarray]:
    """Create one fixed scanner position per square with multiple camera rotations."""
    number_of_angles = max(1, int(number_of_angles))
    points: list[np.ndarray] = []
    station_ids: list[int] = []
    view_names: list[str] = []
    rotvecs: list[np.ndarray] = []
    tilt = min(0.60, max(0.0, float(view_radius) / 0.060 * 0.45))

    for station_id, station in enumerate(stations):
        for angle_index in range(number_of_angles):
            theta = 2.0 * math.pi * angle_index / number_of_angles
            angle_deg = 360.0 * angle_index / number_of_angles
            offset = np.array([0.0, 0.0, angle_lift], dtype=float)
            rotvec = np.array(
                [
                    math.pi,
                    tilt * math.sin(theta),
                    tilt * math.cos(theta),
                ],
                dtype=float,
            )
            points.append(station + offset)
            station_ids.append(station_id)
            view_names.append(f"angle {angle_deg:.0f}")
            rotvecs.append(rotvec)
    return np.asarray(points), station_ids, view_names, np.asarray(rotvecs)


def resolve_fabric_grid(args) -> None:
    args.rows = max(1, int(args.rows))
    args.cols = max(1, int(args.cols))
    args.square_width = args.width / max(1, args.cols)
    args.square_length = args.length / max(1, args.rows)


def build_plan(args) -> FabricPlan:
    resolve_fabric_grid(args)
    model_curves = getattr(args, "model_curves", None)
    if model_curves is None:
        model_curves = _load_saved_model_curves(getattr(args, "model_json", ""))
    else:
        model_curves = [np.asarray(curve, dtype=np.float32) for curve in model_curves if len(curve) > 1]
        if not model_curves:
            model_curves = _load_saved_model_curves(getattr(args, "model_json", ""))
    raw_stations, station_cells, station_colors, cell_color_sets = build_fabric_grid_stations(
        width=args.width,
        length=args.length,
        rows=args.rows,
        cols=args.cols,
        edge_margin=args.edge_margin,
        square_margin=args.square_margin,
        surface_wave=args.surface_wave,
        palette=getattr(args, "palette", None),
        cell_color_sets=getattr(args, "cell_color_sets", None),
    )
    cell_model_curves = _normalize_cell_model_curves(
        getattr(args, "cell_model_curves", None),
        args.rows,
        args.cols,
    )
    if cell_model_curves is None and bool(getattr(args, "random_patterns", False)):
        cell_model_curves = _generate_random_cell_model_curves(args)
        if cell_model_curves:
            model_curves = cell_model_curves[0]
    raw_points, station_ids, view_names, rotvecs = expand_stations_to_angle_viewpoints(
        raw_stations,
        number_of_angles=args.number_of_angles,
        view_radius=args.view_radius,
        angle_lift=args.angle_lift,
    )

    lift = np.array([0.0, 0.0, args.approach_lift])
    raw_points = np.vstack([raw_points[0] + lift, raw_points, raw_points[-1] + lift])
    station_ids = [station_ids[0], *station_ids, station_ids[-1]]
    view_names = ["approach", *view_names, "retreat"]
    rotvecs = np.vstack([TOOL_DOWN_ROTVEC, rotvecs, TOOL_DOWN_ROTVEC])

    center = np.asarray(args.center, dtype=float)
    max_span = np.asarray(args.max_span, dtype=float)
    mapped_stations = fit_path_to_workspace(raw_stations, center=center, max_span=max_span)
    mapped_points = fit_path_to_workspace(raw_points, center=center, max_span=max_span)
    poses = points_and_rotvecs_to_poses(mapped_points, rotvecs)

    fabric_xy = mapped_stations[:, :2]
    fabric_origin = np.array([fabric_xy[:, 0].min(), fabric_xy[:, 1].min(), mapped_stations[:, 2].min()])
    fabric_size = np.array([np.ptp(fabric_xy[:, 0]), np.ptp(fabric_xy[:, 1]), 0.0])

    return FabricPlan(
        raw_stations=raw_stations,
        mapped_stations=mapped_stations,
        raw_points=raw_points,
        mapped_points=mapped_points,
        poses=poses,
        station_ids=station_ids,
        view_names=view_names,
        station_cells=station_cells,
        cell_colors=station_colors,
        cell_color_sets=cell_color_sets,
        fabric_origin=fabric_origin,
        fabric_size=fabric_size,
        grid_rows=args.rows,
        grid_cols=args.cols,
        square_width=args.square_width,
        square_length=args.square_length,
        model_curves=model_curves,
        cell_model_curves=cell_model_curves,
        pattern_repeat_rows=max(1, int(getattr(args, "pattern_repeat_rows", 1))),
        pattern_repeat_cols=max(1, int(getattr(args, "pattern_repeat_cols", 1))),
        pattern_repeat_spacing_x=float(np.clip(float(getattr(args, "pattern_repeat_spacing_x", 1.0)), 0.55, 1.45)),
        pattern_repeat_spacing_y=float(np.clip(float(getattr(args, "pattern_repeat_spacing_y", 1.0)), 0.55, 1.45)),
        batch_texture_width=int(np.clip(int(getattr(args, "batch_texture_width", 420)), 160, 2048)),
        batch_texture_height=int(np.clip(int(getattr(args, "batch_texture_height", 340)), 120, 1660)),
        scanner_lighting=_scanner_lighting_from_args(args),
        display_batch_colors=_normalize_batch_display_colors(getattr(args, "display_batch_colors", None), args.rows * args.cols),
    )


def densify_plan_for_robot(plan: FabricPlan, max_step: float = ROBOT_MAX_CARTESIAN_STEP) -> FabricPlan:
    if max_step <= 0 or len(plan.poses) < 2:
        return plan

    poses: list[np.ndarray] = [plan.poses[0].copy()]
    station_ids: list[int] = [plan.station_ids[0]]
    view_names: list[str] = [plan.view_names[0]]

    for index in range(1, len(plan.poses)):
        start = plan.poses[index - 1]
        end = plan.poses[index]
        distance = float(np.linalg.norm(end[:3] - start[:3]))
        steps = max(1, int(math.ceil(distance / max_step)))

        for step in range(1, steps + 1):
            t = step / steps
            pose = (1.0 - t) * start + t * end
            poses.append(pose)
            station_ids.append(plan.station_ids[index])
            view_names.append(plan.view_names[index] if step == steps else "travel")

    dense_poses = np.asarray(poses, dtype=float)
    return replace(
        plan,
        mapped_points=dense_poses[:, :3].copy(),
        poses=dense_poses,
        station_ids=station_ids,
        view_names=view_names,
    )


def is_scan_view(view_name: str) -> bool:
    return view_name not in NON_SCAN_VIEW_NAMES


def should_save_scan_image(
    args,
    plan: FabricPlan,
    target_index: int,
    saved_targets: set[int],
    saved_stations: set[int],
    save_images: bool | None = None,
) -> bool:
    if save_images is None:
        save_images = bool(args.save_images)
    if not save_images or target_index in saved_targets:
        return False
    view_name = plan.view_names[target_index]
    if not is_scan_view(view_name):
        return False
    station = plan.station_ids[target_index]
    if args.image_every == CAMERA_SAVE_EVERY_STATION:
        return station not in saved_stations
    return True


def rot_from_wxyz(q: np.ndarray) -> Rotation:
    return Rotation.from_quat([q[1], q[2], q[3], q[0]])


def load_ur5e_model_data():
    import mujoco
    from robot_descriptions import ur5e_mj_description

    model = mujoco.MjModel.from_xml_path(ur5e_mj_description.MJCF_PATH)
    data = mujoco.MjData(model)
    site_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_SITE, "attachment_site")
    if site_id < 0:
        raise RuntimeError("UR5e MJCF does not contain site 'attachment_site'")

    # Keep the simulated UR5 base frame rotated exactly 180 degrees around Z,
    # then start joint 1 at zero. This rotates the robot placement itself
    # instead of twisting the shoulder joint to fake the direction.
    base_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, "base")
    if base_id >= 0:
        model.body_quat[base_id] = np.array([0.0, 0.0, 0.0, 1.0], dtype=float)
    data.qpos[:6] = [0.0, -np.pi / 2, np.pi / 2, -np.pi / 2, -np.pi / 2, 0.0]
    mujoco.mj_forward(model, data)
    return mujoco, model, data, site_id


# ============================================================================
# Scanning Section: Robot Pose and IK Helpers
# ============================================================================

def get_tcp(mujoco, model, data, site_id) -> np.ndarray:
    q = np.empty(4)
    mujoco.mju_mat2Quat(q, data.site_xmat[site_id])
    rotvec = rot_from_wxyz(q).as_rotvec()
    return np.r_[data.site_xpos[site_id].copy(), rotvec]


def step_ik(mujoco, model, data, site_id, target_pose: np.ndarray) -> None:
    cur = get_tcp(mujoco, model, data, site_id)
    err_pos = target_pose[:3] - cur[:3]
    err_rot = (Rotation.from_rotvec(target_pose[3:6]) * Rotation.from_rotvec(cur[3:6]).inv()).as_rotvec()
    jacp = np.zeros((3, model.nv))
    jacr = np.zeros((3, model.nv))
    mujoco.mj_jacSite(model, data, jacp, jacr, site_id)
    jac = np.vstack([jacp[:, :6], jacr[:, :6]])
    err = MUJOCO_KP * np.r_[err_pos, 0.35 * err_rot]
    jjt = jac @ jac.T
    dq = jac.T @ np.linalg.solve(jjt + (MUJOCO_DAMPING**2) * np.eye(jjt.shape[0]), err)
    data.qpos[:6] = np.clip(data.qpos[:6] + dq, model.jnt_range[:6, 0], model.jnt_range[:6, 1])
    mujoco.mj_forward(model, data)


def pose_errors(current_pose: np.ndarray, target_pose: np.ndarray) -> tuple[float, float]:
    pos_err = float(np.linalg.norm(current_pose[:3] - target_pose[:3]))
    rot_err = (
        Rotation.from_rotvec(target_pose[3:6])
        * Rotation.from_rotvec(current_pose[3:6]).inv()
    ).magnitude()
    return pos_err, float(rot_err)


# ============================================================================
# Scanning Section: MuJoCo Scene Drawing and Fabric Proxy
# ============================================================================

def _add_sphere(mujoco, scn, pos, radius, rgba):
    if scn.ngeom >= scn.maxgeom:
        return
    mujoco.mjv_initGeom(
        scn.geoms[scn.ngeom],
        mujoco.mjtGeom.mjGEOM_SPHERE,
        np.array([radius, 0.0, 0.0]),
        np.asarray(pos, dtype=float),
        np.eye(3).flatten(),
        np.asarray(rgba, dtype=np.float32),
    )
    scn.ngeom += 1


def _add_box(mujoco, scn, pos, size, rgba):
    if scn.ngeom >= scn.maxgeom:
        return
    mujoco.mjv_initGeom(
        scn.geoms[scn.ngeom],
        mujoco.mjtGeom.mjGEOM_BOX,
        np.asarray(size, dtype=float),
        np.asarray(pos, dtype=float),
        np.eye(3).flatten(),
        np.asarray(rgba, dtype=np.float32),
    )
    scn.ngeom += 1


def _cell_color_set(plan: FabricPlan, row: int, col: int) -> list[tuple[float, float, float, float]]:
    idx = row * plan.grid_cols + col
    if 0 <= idx < len(plan.cell_color_sets):
        return plan.cell_color_sets[idx]
    return _default_cell_color_set(row, col)


def _cell_model_curves(plan: FabricPlan, row: int, col: int) -> list[np.ndarray]:
    idx = row * plan.grid_cols + col
    if plan.cell_model_curves is not None and 0 <= idx < len(plan.cell_model_curves):
        curves = plan.cell_model_curves[idx]
        if curves:
            return curves
    return plan.model_curves


def _smooth_curve_2d(curve: np.ndarray, samples_per_segment: int = 4, max_points: int = 36) -> np.ndarray:
    pts = np.asarray(curve, dtype=np.float32)[:, :2]
    if pts.shape[0] < 3:
        return pts
    samples_per_segment = max(1, int(samples_per_segment))
    padded = np.vstack([pts[0], pts, pts[-1]])
    smooth = []
    for i in range(1, len(padded) - 2):
        p0, p1, p2, p3 = padded[i - 1], padded[i], padded[i + 1], padded[i + 2]
        for step in range(samples_per_segment):
            t = step / float(samples_per_segment)
            t2 = t * t
            t3 = t2 * t
            point = 0.5 * (
                (2.0 * p1)
                + (-p0 + p2) * t
                + (2.0 * p0 - 5.0 * p1 + 4.0 * p2 - p3) * t2
                + (-p0 + 3.0 * p1 - 3.0 * p2 + p3) * t3
            )
            smooth.append(point)
    smooth.append(pts[-1])
    out = np.asarray(smooth, dtype=np.float32)
    if out.shape[0] > max_points:
        keep = np.linspace(0, out.shape[0] - 1, max_points).astype(int)
        out = out[keep]
    return out


def _smoothed_cell_model_curves(plan: FabricPlan, row: int, col: int) -> list[np.ndarray]:
    cache = getattr(plan, "_smoothed_curve_cache", None)
    if cache is None:
        cache = {}
        setattr(plan, "_smoothed_curve_cache", cache)
    key = (int(row), int(col))
    if key not in cache:
        cache[key] = [_smooth_curve_2d(curve) for curve in _cell_model_curves(plan, row, col)]
    return cache[key]


def _knit_cell_curves() -> list[list[tuple[float, float]]]:
    return [
        [(-0.48, 0.16), (-0.33, 0.38), (-0.08, 0.47), (0.18, 0.43), (0.40, 0.24), (0.30, 0.08), (0.06, -0.02), (-0.20, 0.02), (-0.40, 0.14)],
        [(-0.48, -0.02), (-0.26, 0.06), (-0.05, 0.22), (0.18, 0.08), (0.46, -0.02), (0.22, -0.16), (0.02, -0.31), (-0.20, -0.16), (-0.42, -0.03)],
        [(-0.50, -0.18), (-0.24, -0.14), (0.00, -0.10), (0.24, -0.14), (0.50, -0.18)],
        [(-0.42, -0.30), (-0.25, -0.45), (0.02, -0.48), (0.28, -0.42), (0.44, -0.25), (0.27, -0.09), (0.02, 0.00), (-0.22, -0.10), (-0.44, -0.26)],
    ]


def _add_model_cell_fabric(mujoco, scn, plan: FabricPlan, row: int, col: int, z: float, highlight=False, simplified=False) -> None:
    cell_w = plan.fabric_size[0] / plan.grid_cols
    cell_l = plan.fabric_size[1] / plan.grid_rows
    center_x = plan.fabric_origin[0] + cell_w * (col + 0.5)
    center_y = plan.fabric_origin[1] + cell_l * (row + 0.5)
    colors = _cell_color_set(plan, row, col)
    _add_box(
        mujoco,
        scn,
        [center_x, center_y, z - FABRIC_THICKNESS * 0.25],
        [cell_w * 0.50, cell_l * 0.50, FABRIC_THICKNESS * 0.25],
        (0.018, 0.022, 0.030, 1.0),
    )
    repeat_rows = max(1, int(plan.pattern_repeat_rows))
    repeat_cols = max(1, int(plan.pattern_repeat_cols))
    tile_w = cell_w / repeat_cols
    tile_l = cell_l / repeat_rows
    yarn_width = max(min(tile_w, tile_l) * 0.050, 0.00075)
    z_step = max(FABRIC_THICKNESS * 0.25, yarn_width * 0.35)
    curves = _smoothed_cell_model_curves(plan, row, col)
    image_repeat_proxy = repeat_rows > 1 or repeat_cols > 1
    x0 = center_x - cell_w * 0.5
    y0 = center_y - cell_l * 0.5
    for tr in range(repeat_rows):
        for tc in range(repeat_cols):
            tile_cx = x0 + (tc + 0.5) * tile_w
            tile_cy = y0 + (tr + 0.5) * tile_l
            for curve_idx, curve in enumerate(curves):
                color = colors[curve_idx % len(colors)]
                rgba = (color[0], color[1], color[2], 1.0)
                pts = [
                    np.array([
                        tile_cx + float(p[0]) * tile_w * IMAGE_REPEAT_OVERLAP,
                        tile_cy + float(p[1]) * tile_l * IMAGE_REPEAT_OVERLAP,
                        z + FABRIC_THICKNESS * 0.65 + (0 if image_repeat_proxy else (curve_idx % len(colors))) * z_step,
                    ])
                    for p in curve
                ]
                for a, b in zip(pts, pts[1:]):
                    _add_segment(mujoco, scn, a, b, rgba, yarn_width)
    if highlight:
        _add_box(
            mujoco,
            scn,
            [center_x, center_y, z + FABRIC_THICKNESS * 0.12],
            [cell_w * 0.50, cell_l * 0.50, FABRIC_THICKNESS * 0.12],
            (0.1, 1.0, 0.3, 0.20),
        )


def _add_rendered_fabric_proxy(mujoco, scn, plan: FabricPlan, z: float, view_name: str = "angle 0") -> bool:
    texture = _lit_rendered_texture_for_camera(plan, 0, 0, focused=False, view_name=view_name)
    # This path samples the image directly, and only ever asks for a coarse grid
    # of colours, so a lazy texture is stamped out small.
    texture = _materialize_texture(texture, 1024)
    if texture is None:
        return False
    tex_w, tex_h = texture.size
    if tex_w <= 1 or tex_h <= 1:
        return False
    sample_cols = min(72, max(18, int(plan.grid_cols * 14)))
    sample_rows = min(54, max(14, int(plan.grid_rows * 12)))
    resample = getattr(getattr(Image, "Resampling", Image), "BILINEAR", Image.BILINEAR)
    sampled = np.asarray(texture.resize((sample_cols, sample_rows), resample), dtype=np.float32) / 255.0
    cell_w = plan.fabric_size[0] / sample_cols
    cell_l = plan.fabric_size[1] / sample_rows
    origin_x = plan.fabric_origin[0]
    origin_y = plan.fabric_origin[1]
    for r in range(sample_rows):
        for c in range(sample_cols):
            color = sampled[r, c]
            if float(color.max()) < 0.035:
                continue
            x = origin_x + (c + 0.5) * cell_w
            y = origin_y + (sample_rows - r - 0.5) * cell_l
            _add_box(
                mujoco,
                scn,
                [x, y, z + FABRIC_THICKNESS * 0.18],
                [cell_w * 0.52, cell_l * 0.52, FABRIC_THICKNESS * 0.07],
                (float(color[0]), float(color[1]), float(color[2]), 1.0),
            )
    return True


def _add_batch_result_overlay(mujoco, scn, plan: FabricPlan, z: float, active_cell: tuple[int, int]) -> None:
    colors = plan.display_batch_colors
    if not colors:
        return

    cell_w = plan.fabric_size[0] / max(1, plan.grid_cols)
    cell_l = plan.fabric_size[1] / max(1, plan.grid_rows)
    overlay_z = z + FABRIC_THICKNESS * 0.36
    border_z = z + FABRIC_THICKNESS * 0.50
    for row in range(plan.grid_rows):
        for col in range(plan.grid_cols):
            idx = row * plan.grid_cols + col
            if idx >= len(colors):
                continue
            color = colors[idx]
            center_x = plan.fabric_origin[0] + cell_w * (col + 0.5)
            center_y = plan.fabric_origin[1] + cell_l * (row + 0.5)
            _add_box(
                mujoco,
                scn,
                [center_x, center_y, overlay_z],
                [cell_w * 0.492, cell_l * 0.492, FABRIC_THICKNESS * 0.055],
                (float(color[0]), float(color[1]), float(color[2]), 0.48),
            )
            border_color = (1.0, 0.78, 0.12, 0.95) if (row, col) == active_cell else (0.25, 0.90, 1.0, 0.50)
            corners = [
                np.array([center_x - cell_w * 0.50, center_y - cell_l * 0.50, border_z]),
                np.array([center_x + cell_w * 0.50, center_y - cell_l * 0.50, border_z]),
                np.array([center_x + cell_w * 0.50, center_y + cell_l * 0.50, border_z]),
                np.array([center_x - cell_w * 0.50, center_y + cell_l * 0.50, border_z]),
            ]
            for a, b in zip(corners, corners[1:] + corners[:1]):
                _add_segment(mujoco, scn, a, b, border_color, max(min(cell_w, cell_l) * 0.006, 0.0008))


def _add_segment(mujoco, scn, a, b, rgba, width=PATH_WIDTH):
    if scn.ngeom >= scn.maxgeom:
        return
    geom = scn.geoms[scn.ngeom]
    mujoco.mjv_initGeom(
        geom,
        mujoco.mjtGeom.mjGEOM_CAPSULE,
        np.zeros(3),
        np.zeros(3),
        np.eye(3).flatten(),
        np.asarray(rgba, dtype=np.float32),
    )
    mujoco.mjv_connector(geom, mujoco.mjtGeom.mjGEOM_CAPSULE, width, np.asarray(a), np.asarray(b))
    scn.ngeom += 1


def _add_camera_marker(mujoco, scn, tcp_pos: np.ndarray, look_at: np.ndarray) -> None:
    _add_box(mujoco, scn, tcp_pos, CAMERA_MARKER_SIZE, (0.02, 0.02, 0.02, 1.0))
    direction = np.asarray(look_at, dtype=float) - np.asarray(tcp_pos, dtype=float)
    norm = float(np.linalg.norm(direction))
    if norm > 1e-9:
        tip = np.asarray(tcp_pos, dtype=float) + direction / norm * 0.055
        _add_segment(mujoco, scn, tcp_pos, tip, (0.05, 0.55, 1.0, 0.95), 0.004)


def _add_pose_axes(mujoco, scn, pose: np.ndarray, scale: float = POSE_AXIS_LENGTH, alpha: float = 0.85) -> None:
    origin = np.asarray(pose[:3], dtype=float)
    axes = Rotation.from_rotvec(pose[3:6]).as_matrix()
    colors = (
        (1.0, 0.15, 0.15, alpha),
        (0.10, 0.85, 0.20, alpha),
        (0.15, 0.45, 1.0, alpha),
    )
    for axis_index, color in enumerate(colors):
        _add_segment(mujoco, scn, origin, origin + axes[:, axis_index] * scale, color, 0.0024)


def _add_rotation_ring(mujoco, scn, center: np.ndarray, radius: float, rgba) -> None:
    points = []
    z = float(center[2]) + 0.010
    for index in range(25):
        theta = 2.0 * math.pi * index / 24
        points.append(np.array([center[0] + radius * math.cos(theta), center[1] + radius * math.sin(theta), z]))
    for a, b in zip(points, points[1:]):
        _add_segment(mujoco, scn, a, b, rgba, 0.0015)


# ============================================================================
# Scanning Section: Image-Based Fabric Repeats
# ============================================================================

def _perspective_coeffs(dst_points, src_points):
    matrix = []
    vector = []
    for (x, y), (u, v) in zip(dst_points, src_points):
        matrix.append([x, y, 1.0, 0.0, 0.0, 0.0, -u * x, -u * y])
        matrix.append([0.0, 0.0, 0.0, x, y, 1.0, -v * x, -v * y])
        vector.extend([u, v])
    return np.linalg.solve(np.asarray(matrix, dtype=float), np.asarray(vector, dtype=float)).tolist()


def _materialize_texture(texture, max_dim=None):
    """Accepts a PIL image, or a lazy tiled-texture descriptor from the GUI.

    Scan Mode hands over one seamless period tile plus its repeat counts rather
    than a fully glued image -- the glued form is exact integer repetition, so
    at 64 repeats it is hundreds of MB holding a couple of hundred KB of real
    content. Asking it for `max_dim` stamps the tile out at that size.
    """
    if texture is None:
        return None
    rasterize = getattr(texture, "rasterize", None)
    if rasterize is None:
        return texture
    return rasterize(max_dim)


def _paste_projected_texture(base: Image.Image, texture, projected_quad) -> bool:
    if any(point is None for point in projected_quad):
        return False
    dst = [(float(point[0]), float(point[1])) for point in projected_quad]
    # Deliberately materialised at full resolution rather than at the quad's
    # on-screen size. Pre-filtering the source to roughly what the warp can
    # resolve is cheaper and, judged on its own, cleaner -- Image.transform
    # point-samples with a bicubic kernel and does not area-average, so a large
    # source aliases. But it changes the captured pixels (measured: ~13% of them
    # by more than 8/255 at a 2x pre-filter), and these captures are the
    # scanner's output data. Full resolution keeps every saved image identical
    # to what the glued-image pipeline produced. The memory win is unaffected:
    # this is one transient rasterisation per capture instead of a permanently
    # held glued image per cell.
    texture = _materialize_texture(texture, None)
    src = texture.convert("RGB")
    src_w, src_h = src.size
    if src_w <= 1 or src_h <= 1:
        return False
    src_quad = [(0.0, 0.0), (float(src_w), 0.0), (float(src_w), float(src_h)), (0.0, float(src_h))]
    try:
        coeffs = _perspective_coeffs(dst, src_quad)
    except np.linalg.LinAlgError:
        return False
    resample = getattr(getattr(Image, "Resampling", Image), "BICUBIC", Image.BICUBIC)
    warped = src.transform(base.size, Image.Transform.PERSPECTIVE, coeffs, resample=resample)
    mask_src = Image.new("L", (src_w, src_h), 255)
    mask = mask_src.transform(base.size, Image.Transform.PERSPECTIVE, coeffs, resample=resample)
    base.paste(warped, (0, 0), mask)
    return True


def _trim_rendered_texture(texture: Image.Image) -> Image.Image:
    texture = texture.convert("RGB")
    arr = np.asarray(texture, dtype=np.uint8)
    if arr.size == 0:
        return texture
    edge = np.concatenate([
        arr[:4, :, :].reshape(-1, 3),
        arr[-4:, :, :].reshape(-1, 3),
        arr[:, :4, :].reshape(-1, 3),
        arr[:, -4:, :].reshape(-1, 3),
    ])
    bg = np.median(edge, axis=0)
    diff = np.linalg.norm(arr.astype(np.float32) - bg.astype(np.float32), axis=2)
    mask = (diff > 14.0) | (arr.max(axis=2) > 55)
    ys, xs = np.where(mask)
    if xs.size < 16 or ys.size < 16:
        return texture
    pad = 0
    x0 = max(0, int(xs.min()) - pad)
    x1 = min(texture.size[0], int(xs.max()) + pad + 1)
    y0 = max(0, int(ys.min()) - pad)
    y1 = min(texture.size[1], int(ys.max()) + pad + 1)
    return texture.crop((x0, y0, x1, y1))


def _tile_rendered_texture(
    texture: Image.Image,
    repeat_rows: int,
    repeat_cols: int,
    spacing_x: float = 1.0,
    spacing_y: float = 1.0,
) -> Image.Image:
    repeat_rows = max(1, int(repeat_rows))
    repeat_cols = max(1, int(repeat_cols))
    spacing_x = float(np.clip(float(spacing_x), 0.55, 1.45))
    spacing_y = float(np.clip(float(spacing_y), 0.55, 1.45))
    tile = _trim_rendered_texture(texture)
    tile_w, tile_h = tile.size
    if tile_w <= 1 or tile_h <= 1:
        return tile
    max_dim = 2048
    step_w = max(1, int(round(tile_w * spacing_x)))
    step_h = max(1, int(round(tile_h * spacing_y)))
    canvas_w = step_w * (repeat_cols - 1) + tile_w
    canvas_h = step_h * (repeat_rows - 1) + tile_h
    scale = min(1.0, max_dim / max(float(canvas_w), 1.0), max_dim / max(float(canvas_h), 1.0))
    if scale < 1.0:
        resample = getattr(getattr(Image, "Resampling", Image), "LANCZOS", Image.LANCZOS)
        tile = tile.resize((max(1, int(tile_w * scale)), max(1, int(tile_h * scale))), resample)
        tile_w, tile_h = tile.size
        step_w = max(1, int(round(tile_w * spacing_x)))
        step_h = max(1, int(round(tile_h * spacing_y)))
    canvas_w = step_w * (repeat_cols - 1) + tile_w
    canvas_h = step_h * (repeat_rows - 1) + tile_h
    canvas = Image.new("RGB", (canvas_w, canvas_h), (18, 22, 28))
    for r in range(repeat_rows):
        for c in range(repeat_cols):
            canvas.paste(tile, (c * step_w, r * step_h))
    return canvas


def _render_cell_pattern_texture(plan: FabricPlan, row: int, col: int, width: int = 420, height: int = 340) -> Image.Image:
    """Render one knitted fabric sample before image-based repetition."""
    from PIL import ImageDraw

    scale = 3
    width = max(96, int(width))
    height = max(80, int(height))
    canvas = Image.new("RGB", (width * scale, height * scale), (18, 23, 31))
    draw = ImageDraw.Draw(canvas)
    colors = _cell_color_set(plan, row, col)
    curves = _smoothed_cell_model_curves(plan, row, col)
    if not curves:
        return canvas.resize((width, height), getattr(getattr(Image, "Resampling", Image), "LANCZOS", Image.LANCZOS))

    all_pts = np.vstack([curve[:, :2] for curve in curves if len(curve) > 1])
    min_xy = all_pts.min(axis=0)
    max_xy = all_pts.max(axis=0)
    center = (min_xy + max_xy) * 0.5
    span = np.maximum(max_xy - min_xy, 1e-6)
    usable_w = width * scale * 0.84
    usable_h = height * scale * 0.84
    px_scale = min(usable_w / float(span[0]), usable_h / float(span[1]))
    origin = np.array([width * scale * 0.5, height * scale * 0.5], dtype=np.float32)
    line_w = max(2, int(min(width, height) * scale * 0.030))
    shade_w = max(line_w + 2, int(line_w * 1.65))

    for curve_idx, curve in enumerate(curves):
        if len(curve) < 2:
            continue
        rgba = colors[curve_idx % len(colors)]
        color = tuple(int(255 * float(v)) for v in rgba[:3])
        shadow = tuple(max(0, int(channel * 0.32)) for channel in color)
        highlight = tuple(min(255, int(channel * 1.18 + 18)) for channel in color)
        pts = [
            (
                int(round(origin[0] + (float(p[0]) - center[0]) * px_scale)),
                int(round(origin[1] - (float(p[1]) - center[1]) * px_scale)),
            )
            for p in curve
        ]
        draw.line(pts, fill=shadow, width=shade_w, joint="curve")
        draw.line(pts, fill=color, width=line_w, joint="curve")
        if line_w >= 5:
            offset_pts = [(x - max(1, line_w // 5), y - max(1, line_w // 5)) for x, y in pts]
            draw.line(offset_pts, fill=highlight, width=max(1, line_w // 4), joint="curve")

    resample = getattr(getattr(Image, "Resampling", Image), "LANCZOS", Image.LANCZOS)
    return canvas.resize((width, height), resample)


def _view_angle_degrees(view_name: str) -> float:
    text = str(view_name).lower()
    if "angle" not in text:
        return 0.0
    try:
        return float(text.split("angle", 1)[1].strip().split()[0])
    except (IndexError, ValueError):
        return 0.0


def _apply_scanner_lighting(texture: Image.Image, view_name: str, focused: bool, lighting_settings=None) -> Image.Image:
    """Apply the scanner's image-space lighting to a rendered fabric texture.

    Focused captures call this on one rendered pattern unit before image tiling.
    Full-layout captures may call it on the assembled preview image when that
    preview has not already been lit. Preview and saved images use this same
    function, so the selected lighting mode stays consistent.
    """
    src = texture.convert("RGB")
    arr = np.asarray(src, dtype=np.float32) / 255.0
    if arr.ndim != 3 or arr.shape[0] < 3 or arr.shape[1] < 3:
        return src
    lighting = _normalize_scanner_lighting(lighting_settings)
    if lighting["enabled"] < 0.5:
        return src

    h, w = arr.shape[:2]
    luminance = (
        arr[:, :, 0] * 0.299
        + arr[:, :, 1] * 0.587
        + arr[:, :, 2] * 0.114
    )
    lum_u8 = np.clip(luminance * 255.0, 0, 255).astype(np.uint8)
    smooth_luminance = (
        np.asarray(
            Image.fromarray(lum_u8, "L").filter(ImageFilter.GaussianBlur(lighting["blur"])),
            dtype=np.float32,
        )
        / 255.0
    )
    gy, gx = np.gradient(smooth_luminance)
    relief = lighting["focused_relief"] if focused else lighting["relief"]
    normals = np.dstack((-gx * relief, -gy * relief, np.ones_like(luminance)))
    normals /= np.maximum(np.linalg.norm(normals, axis=2, keepdims=True), 1e-6)

    angle = math.radians(_view_angle_degrees(view_name))
    sun_azimuth = math.radians(lighting["azimuth"])
    sun_elevation = math.radians(lighting["elevation"])
    # A fixed one-sided "sun" in fabric/world coordinates. The camera/fabric
    # view rotates through scan angles while this light stays put, so the same
    # fabric can look slightly different from each viewing angle.
    light_xy = sun_azimuth - angle
    light = np.array(
        [
            math.cos(light_xy) * math.cos(sun_elevation),
            math.sin(light_xy) * math.cos(sun_elevation),
            math.sin(sun_elevation),
        ],
        dtype=np.float32,
    )
    light /= max(float(np.linalg.norm(light)), 1e-6)
    view = np.array([0.0, 0.0, 1.0], dtype=np.float32)
    half_vec = light + view
    half_vec /= max(float(np.linalg.norm(half_vec)), 1e-6)

    diffuse = np.clip(np.sum(normals * light[None, None, :], axis=2), 0.0, 1.0)
    specular = np.clip(np.sum(normals * half_vec[None, None, :], axis=2), 0.0, 1.0) ** 22.0

    yy, xx = np.mgrid[0:h, 0:w].astype(np.float32)
    xx = (xx / max(float(w - 1), 1.0)) - 0.5
    yy = (yy / max(float(h - 1), 1.0)) - 0.5
    directional_falloff = xx * math.cos(light_xy) + yy * math.sin(light_xy)
    broad_light = 1.0 + lighting["shadow"] * directional_falloff
    fabric_gradient = 1.0 + lighting["gradient"] * directional_falloff
    vignette = 1.0 - lighting["vignette"] * np.clip(xx * xx + yy * yy, 0.0, 0.5)

    # Preserve the fabric's actual colors while letting shadows and highlights
    # affect every color equally.
    shade = (lighting["ambient"] + lighting["sun_intensity"] * diffuse) * broad_light * fabric_gradient * vignette
    shade = np.clip(shade, 0.62, 1.16)
    lit = arr * shade[:, :, None]
    lit += specular[:, :, None] * lighting["specular"]

    # Slight view-dependent yarn sheen. It uses the smoothed luminance map so it
    # reads as a soft material response instead of pixel-level sparkle/noise.
    ridge = np.clip((smooth_luminance - np.percentile(smooth_luminance, 42.0)) * 1.65, 0.0, 1.0)
    sheen_axis = angle - sun_azimuth
    sheen_phase = np.sin((xx * math.cos(sheen_axis) + yy * math.sin(sheen_axis)) * math.pi * 5.5)
    sheen = np.clip(sheen_phase, 0.0, 1.0) * ridge * lighting["sheen"]
    lit += sheen[:, :, None]

    out = np.clip(lit * 255.0, 0, 255).astype(np.uint8)
    return Image.fromarray(out, "RGB")


def _lit_rendered_texture_for_camera(plan: FabricPlan, row: int, col: int, focused: bool, view_name: str, camera_zoom: float = 1.0) -> Image.Image | None:
    repeat_rows = max(1, int(plan.pattern_repeat_rows))
    repeat_cols = max(1, int(plan.pattern_repeat_cols))
    spacing_x = float(np.clip(float(getattr(plan, "pattern_repeat_spacing_x", 1.0)), 0.55, 1.45))
    spacing_y = float(np.clip(float(getattr(plan, "pattern_repeat_spacing_y", 1.0)), 0.55, 1.45))
    lighting = _normalize_scanner_lighting(getattr(plan, "scanner_lighting", None))
    lighting_key = tuple((key, round(float(lighting[key]), 4)) for key in sorted(lighting))
    batch_w = int(np.clip(int(getattr(plan, "batch_texture_width", 420)), 160, 2048))
    batch_h = int(np.clip(int(getattr(plan, "batch_texture_height", 340)), 120, 1660))
    camera_zoom = float(np.clip(float(camera_zoom), 0.2, 8.0))
    cache_key = (
        "lit",
        "cell" if focused else "full",
        int(row),
        int(col),
        repeat_rows,
        repeat_cols,
        round(spacing_x, 3),
        round(spacing_y, 3),
        str(view_name),
        bool(focused),
        batch_w,
        batch_h,
        lighting_key,
        round(camera_zoom, 3),
    )
    cache = getattr(plan, "_rendered_texture_cache", None)
    if cache is None:
        cache = {}
        setattr(plan, "_rendered_texture_cache", cache)
    if cache_key not in cache:
        if focused:
            # A fresh, angle-specific real render (real 3D model duplicated,
            # captured, and exact-period tiled -- the Puzzle Mode workflow
            # automated in gui.py) is the primary source when a live renderer
            # is attached: rendered once per (row, col, angle, zoom) and cached
            # here like every other case, so live preview during robot travel
            # does not re-render every frame but a genuinely new angle does.
            #
            # It can decline. The exact-period crop measures the pattern period
            # in screen pixels, which is only meaningful while the fabric is
            # seen roughly face-on; by ~90 degrees the period projects to almost
            # nothing and the crop would collapse to a sliver. Scans use angles
            # of 360*i/n, so with the usual 4 angles 90 and 270 land exactly
            # there. The renderer returns None for those rather than handing
            # back a smear, and the pre-glued seamless tile is used instead.
            render_fn = getattr(plan, "scan_render_capture_fn", None)
            fresh = render_fn(row, col, _view_angle_degrees(view_name), camera_zoom) if render_fn is not None else None

            # Pre-glued per-pattern tiles: already tiled by the repeat sliders
            # and already lit by the real 3D shader, so no further tiling or 2D
            # lighting post-process is applied.
            scan_tiles = getattr(plan, "scan_tiled_pattern_images", None)
            tile_idx = row * plan.grid_cols + col
            if fresh is not None:
                cache[cache_key] = fresh
            elif scan_tiles and 0 <= tile_idx < len(scan_tiles):
                cache[cache_key] = scan_tiles[tile_idx]
            else:
                # Focused scanner captures use the requested workflow:
                # render one selected pattern unit, apply lighting to that unit,
                # then duplicate the lit image by the repeat sliders.
                cell_texture = _render_cell_pattern_texture(plan, row, col, batch_w, batch_h)
                lit_cell = _apply_scanner_lighting(cell_texture, view_name, focused, lighting)
                cache[cache_key] = _tile_rendered_texture(lit_cell, repeat_rows, repeat_cols, spacing_x, spacing_y)
        else:
            texture = _rendered_texture_for_camera(plan, row, col, focused)
            if texture is None:
                return None
            if bool(getattr(plan, "rendered_fabric_image_lit", False)):
                cache[cache_key] = texture
            else:
                cache[cache_key] = _apply_scanner_lighting(texture, view_name, focused, lighting)
    return cache[cache_key]


def _rendered_texture_for_camera(plan: FabricPlan, row: int, col: int, focused: bool) -> Image.Image | None:
    texture = getattr(plan, "rendered_fabric_image", None)
    if texture is not None:
        texture = texture.convert("RGB")
    source_is_full_layout = bool(getattr(plan, "rendered_fabric_image_is_full_layout", False))
    repeat_rows = max(1, int(plan.pattern_repeat_rows))
    repeat_cols = max(1, int(plan.pattern_repeat_cols))
    spacing_x = float(np.clip(float(getattr(plan, "pattern_repeat_spacing_x", 1.0)), 0.55, 1.45))
    spacing_y = float(np.clip(float(getattr(plan, "pattern_repeat_spacing_y", 1.0)), 0.55, 1.45))
    if not focused:
        if texture is None:
            return None
        if source_is_full_layout:
            return texture
        cache_key = ("full", bool(source_is_full_layout), repeat_rows, repeat_cols, round(spacing_x, 3), round(spacing_y, 3))
        cache = getattr(plan, "_rendered_texture_cache", None)
        if cache is None:
            cache = {}
            setattr(plan, "_rendered_texture_cache", cache)
        if cache_key not in cache:
            cache[cache_key] = _tile_rendered_texture(texture, repeat_rows, repeat_cols, spacing_x, spacing_y)
        return cache[cache_key]
    batch_w = int(np.clip(int(getattr(plan, "batch_texture_width", 420)), 160, 2048))
    batch_h = int(np.clip(int(getattr(plan, "batch_texture_height", 340)), 120, 1660))
    cache_key = (
        "cell_direct",
        int(row),
        int(col),
        repeat_rows,
        repeat_cols,
        round(spacing_x, 3),
        round(spacing_y, 3),
        batch_w,
        batch_h,
    )
    cache = getattr(plan, "_rendered_texture_cache", None)
    if cache is None:
        cache = {}
        setattr(plan, "_rendered_texture_cache", cache)
    if cache_key not in cache:
        cell_texture = _render_cell_pattern_texture(plan, row, col, batch_w, batch_h)
        cache[cache_key] = _tile_rendered_texture(cell_texture, repeat_rows, repeat_cols, spacing_x, spacing_y)
    return cache[cache_key]


def draw_scene(
    mujoco,
    handle,
    plan: FabricPlan,
    target_index: int,
    executed: list[np.ndarray],
    camera_enabled: bool = False,
    current_pose: np.ndarray | None = None,
    target_pose: np.ndarray | None = None,
    clear_scene: bool = True,
    simplified: bool = False,
) -> None:
    scn = handle.user_scn
    if clear_scene:
        scn.ngeom = 0

    cell_w = plan.fabric_size[0] / plan.grid_cols
    cell_l = plan.fabric_size[1] / plan.grid_rows
    z = plan.fabric_origin[2] - FABRIC_THICKNESS * 0.5
    fabric_center = plan.fabric_origin + np.array([plan.fabric_size[0] * 0.5, plan.fabric_size[1] * 0.5, 0.0])
    _add_box(
        mujoco,
        scn,
        [fabric_center[0] - 0.12, fabric_center[1], -0.018],
        [0.62, 0.42, 0.012],
        (0.10, 0.105, 0.115, 1.0),
    )
    _add_box(
        mujoco,
        scn,
        [fabric_center[0], fabric_center[1], z - FABRIC_THICKNESS * 0.55],
        [plan.fabric_size[0] * 0.54, plan.fabric_size[1] * 0.54, FABRIC_THICKNESS * 0.16],
        (0.030, 0.036, 0.046, 1.0),
    )
    station_id = plan.station_ids[min(target_index, len(plan.station_ids) - 1)]
    active_cell = plan.station_cells[station_id]
    view_name = plan.view_names[min(target_index, len(plan.view_names) - 1)] if plan.view_names else "angle 0"
    rendered_proxy = _add_rendered_fabric_proxy(mujoco, scn, plan, z, view_name=view_name)
    for row in range(plan.grid_rows):
        for col in range(plan.grid_cols):
            if not rendered_proxy:
                _add_model_cell_fabric(mujoco, scn, plan, row, col, z, highlight=(row, col) == active_cell, simplified=simplified)
            elif (row, col) == active_cell:
                cell_w = plan.fabric_size[0] / plan.grid_cols
                cell_l = plan.fabric_size[1] / plan.grid_rows
                center_x = plan.fabric_origin[0] + cell_w * (col + 0.5)
                center_y = plan.fabric_origin[1] + cell_l * (row + 0.5)
                _add_box(
                    mujoco,
                    scn,
                    [center_x, center_y, z + FABRIC_THICKNESS * 0.28],
                    [cell_w * 0.50, cell_l * 0.50, FABRIC_THICKNESS * 0.08],
                    (0.1, 1.0, 0.3, 0.18),
                )

    _add_batch_result_overlay(mujoco, scn, plan, z, active_cell)

    path_step = max(1, int(math.ceil(len(plan.mapped_points) / 80))) if simplified else 1
    for i in range(0, len(plan.mapped_points) - 1, path_step):
        j = min(i + path_step, len(plan.mapped_points) - 1)
        _add_segment(mujoco, scn, plan.mapped_points[i], plan.mapped_points[j], (0.20, 0.24, 0.30, 0.28), 0.0018)

    if target_index > 0:
        progress_step = max(1, int(math.ceil(target_index / 80))) if simplified else 1
        for i in range(0, min(target_index, len(plan.mapped_points) - 1), progress_step):
            j = min(i + progress_step, len(plan.mapped_points) - 1)
            _add_segment(mujoco, scn, plan.mapped_points[i], plan.mapped_points[j], (0.15, 0.85, 0.35, 0.55), 0.0026)

    trail_limit = min(MAX_TRAIL_POINTS, 60 if simplified else MAX_TRAIL_POINTS)
    trail = executed[-trail_limit:]
    if simplified and len(trail) > 40:
        trail = trail[::max(1, int(math.ceil(len(trail) / 40)))]
    for a, b in zip(trail, trail[1:]):
        _add_segment(mujoco, scn, a, b, (1.00, 0.42, 0.08, 0.90), 0.0032)

    target = plan.mapped_points[min(target_index, len(plan.mapped_points) - 1)]
    station = plan.mapped_stations[station_id]
    color = plan.cell_colors[station_id]
    _add_sphere(mujoco, scn, station, MARKER_RADIUS * 1.15, color)
    _add_sphere(mujoco, scn, target, MARKER_RADIUS * 1.45, (0.1, 1.0, 0.3, 1.0))
    _add_rotation_ring(mujoco, scn, station, min(plan.square_width, plan.square_length) * 0.22, (0.1, 1.0, 0.3, 0.65))
    if target_pose is not None:
        _add_pose_axes(mujoco, scn, target_pose, scale=POSE_AXIS_LENGTH * 1.15, alpha=0.55)
    if current_pose is not None:
        _add_pose_axes(mujoco, scn, current_pose, scale=POSE_AXIS_LENGTH, alpha=0.95)
    if trail:
        _add_sphere(mujoco, scn, trail[-1], MARKER_RADIUS * 1.35, (1.0, 0.42, 0.08, 1.0))
        if camera_enabled:
            _add_camera_marker(mujoco, scn, trail[-1], station)

    handle.sync()


# ============================================================================
# Scanning Section: Robot Camera Capture
# ============================================================================

def _detect_knitting_patch(full_image: Image.Image) -> tuple[tuple[int, int, int, int], float]:
    """Dynamically locates the knitting patch within a captured image instead
    of assuming it always sits in the same predefined region: estimates the
    background from the image border, masks pixels that differ from it and
    look yarn-like (bright + saturated), then takes the largest connected
    component's bounding box.

    Returns ((x0, y0, x1, y1), confidence). confidence in [0, 1] is
    fill_ratio * size_ratio: fill_ratio is how much of the bounding box the
    detected blob actually fills (near 1.0 for a clean solid rectangular
    patch, lower for a scattered/noisy detection), size_ratio penalizes
    implausibly tiny detections relative to the frame. A low score flags an
    unreliable detection for review rather than silently trusting a bad crop.
    """
    rgb = np.asarray(full_image.convert("RGB"), dtype=np.float32)
    h, w = rgb.shape[:2]
    if h < 8 or w < 8:
        return (0, 0, w, h), 0.0

    edge = np.concatenate([
        rgb[:8, :, :].reshape(-1, 3),
        rgb[-8:, :, :].reshape(-1, 3),
        rgb[:, :8, :].reshape(-1, 3),
        rgb[:, -8:, :].reshape(-1, 3),
    ])
    bg = np.median(edge, axis=0)
    diff = np.linalg.norm(rgb - bg[None, None, :], axis=2)
    brightness = rgb.max(axis=2)
    saturation = rgb.max(axis=2) - rgb.min(axis=2)
    mask = (diff > 30.0) & (brightness > 42.0) & (saturation > 16.0)
    if int(mask.sum()) < 32:
        mask = (diff > 18.0) & (brightness > 26.0) & (saturation > 8.0)
    if int(mask.sum()) < 1:
        return (0, 0, w, h), 0.0

    blob = mask
    try:
        from scipy import ndimage
        labeled, num_labels = ndimage.label(mask)
        if num_labels >= 1:
            sizes = ndimage.sum(mask, labeled, index=range(1, num_labels + 1))
            largest_label = int(np.argmax(sizes)) + 1
            blob = labeled == largest_label
    except Exception:
        pass

    ys, xs = np.where(blob)
    if xs.size < 1:
        return (0, 0, w, h), 0.0
    x0, x1 = int(xs.min()), int(xs.max()) + 1
    y0, y1 = int(ys.min()), int(ys.max()) + 1
    bbox_area = max(1, (x1 - x0) * (y1 - y0))
    fill_ratio = float(blob[y0:y1, x0:x1].sum()) / float(bbox_area)
    size_ratio = min(1.0, bbox_area / max(1.0, 0.15 * h * w))
    confidence = float(np.clip(fill_ratio * size_ratio, 0.0, 1.0))
    return (x0, y0, x1, y1), confidence


def render_camera_image(
    plan: FabricPlan,
    tcp_pos: np.ndarray,
    target_index: int,
    station_id: int,
    view_name: str,
    target_pose: np.ndarray | None = None,
    capture_mode: str = CAMERA_CAPTURE_NATURAL,
    camera_zoom: float = 1.0,
    image_size: tuple[int, int] | None = None,
    detect_patch: bool = False,
) -> Image.Image | dict:
    if image_size is None:
        width_px, height_px = CAMERA_IMAGE_SIZE
    else:
        width_px = int(np.clip(int(image_size[0]), 320, 4096))
        height_px = int(np.clip(int(image_size[1]), 240, 3072))
    station = plan.mapped_stations[station_id]
    cell_w = plan.fabric_size[0] / plan.grid_cols
    cell_l = plan.fabric_size[1] / plan.grid_rows
    grid_origin_x = float(plan.mapped_stations[:, 0].min() - cell_w * 0.5)
    grid_origin_y = float(plan.mapped_stations[:, 1].min() - cell_l * 0.5)
    if target_pose is None:
        target_pose = plan.poses[min(target_index, len(plan.poses) - 1)]
    target_pose = np.asarray(target_pose, dtype=float)

    img = Image.new("RGB", (width_px, height_px), (19, 22, 28))

    from PIL import ImageDraw, ImageFilter

    rotation = Rotation.from_rotvec(target_pose[3:6])
    forward = rotation.apply([0.0, 0.0, 1.0])
    forward = forward / max(float(np.linalg.norm(forward)), 1e-8)
    if forward[2] > -0.15:
        forward = station - target_pose[:3]
        forward = forward / max(float(np.linalg.norm(forward)), 1e-8)
    right = rotation.apply([1.0, 0.0, 0.0])
    right = right - forward * float(np.dot(right, forward))
    right = right / max(float(np.linalg.norm(right)), 1e-8)
    up = np.cross(right, forward)
    up = up / max(float(np.linalg.norm(up)), 1e-8)

    active_row, active_col = plan.station_cells[station_id]
    lens_pos = np.asarray(tcp_pos[:3], dtype=float)
    # The tool site is the gripper TCP, while the simulated camera lens sits
    # slightly behind it on the gripper body. This offset gives a real scanner
    # view of the fabric instead of an unusably tiny contact-distance crop.
    focused_capture = str(capture_mode) == CAMERA_CAPTURE_FOCUSED
    rendered_cell_center = np.array(
        [
            grid_origin_x + (active_col + 0.5) * cell_w,
            grid_origin_y + (active_row + 0.5) * cell_l,
            station[2],
        ],
        dtype=float,
    )
    focus = rendered_cell_center + np.array([0.0, 0.0, FABRIC_THICKNESS * 0.15], dtype=float)
    if focused_capture:
        # Focused mode is a batch inspection capture. Use a stable camera
        # centered on the selected batch. The selected scan angle moves the
        # camera around the batch at a shallow oblique angle, not just a flat
        # image roll, so lighting/perspective can affect per-angle RGB.
        angle_deg = 0.0
        if "angle" in str(view_name).lower():
            try:
                angle_deg = float(str(view_name).lower().split("angle", 1)[1].strip().split()[0])
            except (IndexError, ValueError):
                angle_deg = 0.0
        theta = math.radians(angle_deg)
        camera_standoff = max(0.03, max(cell_w, cell_l) * 1.35)
        orbit = max(min(cell_w, cell_l) * 0.22, camera_standoff * 0.18)
        horizontal = np.array([math.cos(theta), math.sin(theta), 0.0], dtype=float)
        lens_pos = focus + horizontal * orbit + np.array([0.0, 0.0, camera_standoff], dtype=float)
        right = np.array([-math.sin(theta), math.cos(theta), 0.0], dtype=float)
    else:
        camera_standoff = max(0.120, max(cell_w, cell_l) * 1.55, float(np.linalg.norm(lens_pos - station)) * 1.75)
        lens_pos = lens_pos - forward * camera_standoff
    # Aim the saved camera at the active station while preserving the roll/right
    # axis from the selected scan angle.
    forward = focus - lens_pos
    camera_standoff = max(float(np.linalg.norm(forward)), 1e-8)
    forward = forward / camera_standoff
    right = right - forward * float(np.dot(right, forward))
    right = right / max(float(np.linalg.norm(right)), 1e-8)
    up = np.cross(right, forward)
    up = up / max(float(np.linalg.norm(up)), 1e-8)

    camera_zoom = max(0.20, float(camera_zoom))
    if focused_capture:
        x_axis = np.array([1.0, 0.0, 0.0], dtype=float)
        y_axis = np.array([0.0, 1.0, 0.0], dtype=float)
        half_view_w = 0.5 * (
            abs(float(np.dot(x_axis, right))) * cell_w
            + abs(float(np.dot(y_axis, right))) * cell_l
        )
        half_view_h = 0.5 * (
            abs(float(np.dot(x_axis, up))) * cell_w
            + abs(float(np.dot(y_axis, up))) * cell_l
        )
        aspect = float(width_px) / max(float(height_px), 1.0)
        # Fill the frame with fabric ("cover" fit: the shorter projected axis
        # sets the zoom) rather than fitting the whole cell with margin on
        # whichever axis doesn't match the image's aspect ratio ("contain"
        # fit). A cell's true aspect rarely matches the capture's fixed 4:3
        # frame, so "contain" always left a visible background gap on one
        # axis; a small amount of edge cropping on the other axis is a much
        # better trade for RGB-analysis accuracy than background pixels are.
        framing_pad = 1.02
        fov_y = 2.0 * math.atan(
            framing_pad
            * min(half_view_h, half_view_w / max(aspect, 1e-6))
            / max(camera_standoff, 1e-6)
        )
        fov_y = float(np.clip(fov_y, math.radians(4.0), math.radians(58.0)))
    else:
        fov_y = math.radians(74.0)
    fov_y = float(np.clip(fov_y / camera_zoom, math.radians(12.0), math.radians(86.0)))
    focal = (height_px * 0.5) / math.tan(fov_y * 0.5)
    near = 0.004

    def project_camera(point: np.ndarray) -> tuple[int, int, float] | None:
        rel = np.asarray(point, dtype=float) - lens_pos
        depth = float(np.dot(rel, forward))
        if depth <= near:
            return None
        camera_x = float(np.dot(rel, right))
        camera_y = float(np.dot(rel, up))
        x = int(width_px * 0.5 + focal * camera_x / depth)
        y = int(height_px * 0.5 - focal * camera_y / depth)
        return x, y, depth

    def visible_line(points: list[np.ndarray]) -> list[tuple[int, int]]:
        out: list[tuple[int, int]] = []
        for point in points:
            projected = project_camera(point)
            if projected is not None:
                x, y, _ = projected
                out.append((x, y))
        return out

    draw = ImageDraw.Draw(img)
    fabric_z = plan.fabric_origin[2] - FABRIC_THICKNESS * 0.48
    rendered_texture = _lit_rendered_texture_for_camera(
        plan,
        active_row,
        active_col,
        focused_capture,
        view_name,
        camera_zoom=camera_zoom,
    )
    if rendered_texture is not None:
        if focused_capture:
            tex_x0 = grid_origin_x + active_col * cell_w
            tex_y0 = grid_origin_y + active_row * cell_l
            tex_x1 = tex_x0 + cell_w
            tex_y1 = tex_y0 + cell_l
        else:
            tex_x0 = grid_origin_x
            tex_y0 = grid_origin_y
            tex_x1 = grid_origin_x + plan.grid_cols * cell_w
            tex_y1 = grid_origin_y + plan.grid_rows * cell_l
        tex_quad = [
            project_camera(np.array([tex_x0, tex_y0, fabric_z + 0.0003])),
            project_camera(np.array([tex_x1, tex_y0, fabric_z + 0.0003])),
            project_camera(np.array([tex_x1, tex_y1, fabric_z + 0.0003])),
            project_camera(np.array([tex_x0, tex_y1, fabric_z + 0.0003])),
        ]
        _paste_projected_texture(img, rendered_texture, tex_quad)
        draw = ImageDraw.Draw(img)

    render_rows = [active_row] if focused_capture else range(plan.grid_rows)
    render_cols = [active_col] if focused_capture else range(plan.grid_cols)
    if rendered_texture is None:
        for row in render_rows:
            for col in render_cols:
                x0 = grid_origin_x + col * cell_w
                y0 = grid_origin_y + row * cell_l
                x1, y1 = x0 + cell_w, y0 + cell_l
                colors = _cell_color_set(plan, row, col)
                cell_poly = [
                    project_camera(np.array([x0, y0, fabric_z])),
                    project_camera(np.array([x1, y0, fabric_z])),
                    project_camera(np.array([x1, y1, fabric_z])),
                    project_camera(np.array([x0, y1, fabric_z])),
                ]
                if all(p is not None for p in cell_poly):
                    draw.polygon([(p[0], p[1]) for p in cell_poly if p is not None], fill=(18, 23, 31))
                depth_to_cell = max(float(np.dot(np.array([x0 + cell_w * 0.5, y0 + cell_l * 0.5, fabric_z]) - lens_pos, forward)), near)
                yarn_px = max(3, min(18, int(focal * max(min(cell_w, cell_l) * 0.030, 0.0014) / depth_to_cell)))
                repeat_rows = max(1, int(plan.pattern_repeat_rows))
                repeat_cols = max(1, int(plan.pattern_repeat_cols))
                tile_w = cell_w / repeat_cols
                tile_l = cell_l / repeat_rows
                curves = _smoothed_cell_model_curves(plan, row, col)
                for tr in range(repeat_rows):
                    for tc in range(repeat_cols):
                        tile_x0 = x0 + tc * tile_w
                        tile_y0 = y0 + tr * tile_l
                        tile_cx = tile_x0 + tile_w * 0.5
                        tile_cy = tile_y0 + tile_l * 0.5
                        for curve_idx, curve in enumerate(curves):
                            rgba = colors[curve_idx % len(colors)]
                            color = tuple(int(255 * c) for c in rgba[:3])
                            shade = tuple(max(0, int(channel * 0.45)) for channel in color)
                            z = fabric_z + curve_idx * max(FABRIC_THICKNESS * 0.08, 0.00045)
                            pts = [
                                np.array([
                                    tile_cx + float(p[0]) * tile_w * IMAGE_REPEAT_OVERLAP,
                                    tile_cy + float(p[1]) * tile_l * IMAGE_REPEAT_OVERLAP,
                                    z,
                                ])
                                for p in curve
                            ]
                            pts2d = visible_line(pts)
                            if len(pts2d) >= 2:
                                draw.line(pts2d, fill=shade, width=max(1, yarn_px // max(repeat_rows, repeat_cols)) + 2, joint="curve")
                                draw.line(pts2d, fill=color, width=max(1, yarn_px // max(repeat_rows, repeat_cols)), joint="curve")

    overlay = Image.new("L", (width_px, height_px), 0)
    mask_draw = ImageDraw.Draw(overlay)
    mask_draw.ellipse([-70, -45, width_px + 70, height_px + 45], fill=255)
    mask = overlay.filter(ImageFilter.GaussianBlur(12))
    dark = Image.new("RGB", (width_px, height_px), (0, 0, 0))
    img = Image.composite(img, dark, mask)
    draw = ImageDraw.Draw(img)
    draw.rectangle([0, 0, 430, 54], fill=(0, 0, 0))
    draw.text((14, 10), f"UR5 camera | station {station_id + 1} | row {active_row + 1}, col {active_col + 1}", fill=(255, 255, 255))
    draw.text(
        (14, 30),
        f"{view_name} | {capture_mode} | repeats {plan.pattern_repeat_rows}x{plan.pattern_repeat_cols} | tcp z {tcp_pos[2]:.3f} m",
        fill=(210, 230, 255),
    )

    if not detect_patch:
        return img

    # Detect the patch from the full image itself (not a fixed assumed
    # region), independently for this specific position/angle/zoom capture.
    (x0, y0, x1, y1), confidence = _detect_knitting_patch(img)
    pad_x = max(2, int(round((x1 - x0) * 0.03)))
    pad_y = max(2, int(round((y1 - y0) * 0.03)))
    crop_box = (
        max(0, x0 - pad_x), max(0, y0 - pad_y),
        min(width_px, x1 + pad_x), min(height_px, y1 + pad_y),
    )
    patch_image = img.crop(crop_box)

    # Debug visualization goes on a *separate* copy -- never on the images
    # used for analysis. Magenta is deliberately distinct from the green
    # debug outline that used to be (mistakenly) baked into saved images.
    debug_image = img.copy()
    debug_draw = ImageDraw.Draw(debug_image)
    debug_color = (255, 40, 200)
    debug_draw.rectangle([x0, y0, max(x0, x1 - 1), max(y0, y1 - 1)], outline=debug_color, width=3)
    debug_draw.text((x0 + 4, max(0, y0 - 16)), f"confidence {confidence:.2f}", fill=debug_color)

    return {
        "full_image": img,
        "patch_image": patch_image,
        "debug_image": debug_image,
        "detection": {
            "bbox": [int(x0), int(y0), int(x1), int(y1)],
            "crop_box": [int(v) for v in crop_box],
            "confidence": float(confidence),
            "zoom": float(camera_zoom),
            "angle_deg": float(_view_angle_degrees(view_name)),
            "camera_pose": {
                "lens_pos": [float(v) for v in lens_pos],
                "forward": [float(v) for v in forward],
                "right": [float(v) for v in right],
                "up": [float(v) for v in up],
                "fov_y_deg": float(math.degrees(fov_y)),
                "standoff": float(camera_standoff),
            },
        },
    }


# ============================================================================
# Real UR5 Execution Section
# ============================================================================

def run_robot_motion(plan: FabricPlan, args) -> None:
    """Send the current scan path to a real UR5 controller."""
    script = generate_urscript(
        plan.poses,
        accel=args.robot_acc,
        vel=args.robot_vel,
        blend_r=0.0,
        dwell=max(args.robot_dwell, 0.0),
        station_ids=plan.station_ids,
        view_names=plan.view_names,
        prog_name="fabric_scanner_real",
    )
    if not script.endswith("\n"):
        script += "\n"

    print(f"[robot] sending URScript to UR5 at {args.robot_ip}:{args.robot_port}")
    print("[robot] robot must be in Remote Control mode before sending.")
    print(f"[robot] poses={len(plan.poses)} vel={args.robot_vel:.3f} acc={args.robot_acc:.3f}")
    try:
        with socket.create_connection((args.robot_ip, args.robot_port), timeout=5.0) as sock:
            sock.sendall(script.encode("utf-8"))
    except OSError as exc:
        raise RuntimeError(f"Could not send URScript to {args.robot_ip}:{args.robot_port}: {exc}") from exc
    print("[robot] program sent. Watch the teach pendant / robot motion for completion.")
